version: '2.1'
orbs:
  node: circleci/node@4.5.1
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          install-yarn: true
          install-npm: false
          lts: true
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run lint
          name: Run YARN lint
      - run:
          command: yarn run test
          name: Run YARN tests
      - run:
          name: Upload to codecov
          command: bash <(curl -s https://codecov.io/bash)
workflows:
  test_my_app:
    jobs:
      - test
