version: 2.1
orbs:
  node: circleci/node@4.2.0
jobs:
  coverage:
    executor: node/default
    steps:
      - run:
          name: Upload to codecov
          command: bash <(curl -s https://codecov.io/bash)
workflows:
  test:
    jobs:
      - node/test:
          pkg-manager: yarn
      - coverage:
          requires:
            - node/test