version: '2.1'
orbs:
  node: circleci/node@4.2.0
jobs:
  test:
    executor:
      name: node/default
      tag: '13'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run lint
          name: Run YARN lint
      - run:
          command: yarn run test
          name: Run YARN tests
      - run:
          name: Upload to codecov
          command: bash <(curl -s https://codecov.io/bash)
workflows:
  test_my_app:
    jobs:
      - test