version: 2.1
orbs:
  node: circleci/node@4.2.0

workflows:
  test:
    jobs:
      - node/test:
          pkg-manager: yarn
      - run:
          name: Upload to codecov
          command: bash <(curl -s https://codecov.io/bash)
